AnchorLayout:

<AnchorLayout>:
    # With those properties we can cahnge change the position of the widget on the screen.
    # anchor_x -> right, left, center: default
    # anchor_y -> bottom, top, center: default
    anchor_x: "center"
    anchor_y: "top"

    BoxLayout:
        size_hint: .3, .3
        spacing: "2dp"

        Button:
            text: "Hallo"

        Button:
            text: "There"
